name: Bridge e2e tests
description: |
  Setup and run bridge e2e tests between tanssi and ethereum

runs:
  using: "composite"
  steps:
    - name: Check g++
      shell: bash
      id: setup_g_plusplus
      run: |
        g++ --version
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
    - name: Check protoc
      shell: bash
      id: check_proto_c
      run: |
        protoc --version
    - name: Check jq
      shell: bash
      id: check_jq
      run: |
        jq --version
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.22.0'
    - name: Check go
      shell: bash
      id: check_go
      run: |
        go version
    - name: Run Mage
      uses: magefile/mage-action@v3
      with:
        install-only: true
    - name: Check mage
      shell: bash
      id: check_mage
      run: |
        mage --version

    # Cache Foundry installation and build artifacts
    - name: Cache Foundry
      uses: actions/cache@v3
      with:
        path: |
          ~/.foundry
          ~/.cache/foundry
        key: foundry-${{ runner.os }}-${{ hashFiles('**/foundry.toml', '**/remappings.txt') }}
        restore-keys: |
          foundry-${{ runner.os }}-

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
    - name: Check forge
      shell: bash
      id: check_forge
      run: |
        forge --version

    # Cache Symbiotic contracts and built artifacts
    - name: Cache Symbiotic Contracts
      uses: actions/cache@v3
      id: cache-symbiotic
      with:
        path: |
          tmp/bridge/tanssi-symbiotic
          tmp/bridge/tanssi-symbiotic/out
          tmp/bridge/tanssi-symbiotic/cache
        key: symbiotic-${{ runner.os }}-${{ hashFiles('**/scripts/bridge/set-env.sh') }}
        restore-keys: |
          symbiotic-${{ runner.os }}-

    # Cache Snowbridge relayer and contracts
    - name: Cache Snowbridge Relayer
      uses: actions/cache@v3
      id: cache-relayer
      with:
        path: |
          tmp/bridge/relayer
          tmp/bridge/relayer/snowbridge/contracts/out
          tmp/bridge/relayer/snowbridge/contracts/cache
        key: relayer-${{ runner.os }}-${{ hashFiles('**/scripts/bridge/set-env.sh') }}
        restore-keys: |
          relayer-${{ runner.os }}-

    - name: Pnpm
      uses: pnpm/action-setup@v4.0.0
      with:
        version: 9
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'pnpm'
    - name: Check date
      shell: bash
      id: check_date
      run: |
        date --version
    - name: Run Zombienet Test zombie_tanssi_relay_eth_bridge
      uses: ./.github/workflow-templates/zombienet-tests
      with:
        test_name: zombie_tanssi_relay_eth_bridge